[package]
name = "serde-gen"
version = "0.1.0"
authors = ["yjh0502 <yjh0502@gmail.com>"]

[dependencies]
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
error-chain = "0.12.4"

clap = "2.33.3"
